<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.6.14">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.6.14">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.trees.REPTree" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-M</object>
            <object class="java.lang.String" name="1">2</object>
            <object class="java.lang.String" name="2">-V</object>
            <object class="java.lang.String" name="3">0.001</object>
            <object class="java.lang.String" name="4">-N</object>
            <object class="java.lang.String" name="5">3</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-L</object>
            <object class="java.lang.String" name="9">-1</object>
            <object class="java.lang.String" name="10"/>
            <object class="java.lang.String" name="11"/>
         </object>
      </object>
      <object class="weka.classifiers.trees.REPTree" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-M</object>
            <object class="java.lang.String" name="1">4</object>
            <object class="java.lang.String" name="2">-V</object>
            <object class="java.lang.String" name="3">0.001</object>
            <object class="java.lang.String" name="4">-N</object>
            <object class="java.lang.String" name="5">3</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-L</object>
            <object class="java.lang.String" name="9">-1</object>
            <object class="java.lang.String" name="10"/>
            <object class="java.lang.String" name="11"/>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">C:/Users/Orysya/Desktop/Data_Mining_III/Data_Files/IMAGE_AssignmentII_bothSets.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">10</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">10</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
               <object class="java.lang.String" name="7"/>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">IMAGE_Experiments.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">C:/Users/Orysya/Desktop/Data_Mining_III/Week7_Summary_Conclusion_Tips_HelpfulGuidance/IMAGE_Experiments.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">true</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
